@echo off
@REM python start_by_file.py --category gui --name AgeCalculator.md
@REM python start_by_file.py --category gui --name BMICalculator.md
@REM python start_by_file.py --category gui --name BookNote.md
@REM python start_by_file.py --category gui --name BookshelfManager.md
@REM python start_by_file.py --category gui --name BusinessTaskScheduler.md
@REM python start_by_file.py --category gui --name CalculationAssistant.md
@REM python start_by_file.py --category gui --name CountdownTimer.md
@REM python start_by_file.py --category gui --name DataSummarizer.md
@REM python start_by_file.py --category gui --name DataVisualizer.md
@REM python start_by_file.py --category gui --name DayPlanner.md
@REM python start_by_file.py --category gui --name ExpenseCategorizer.md
@REM python start_by_file.py --category gui --name ExpenseComparator.md
@REM python start_by_file.py --category gui --name ExpensePlanner.md
@REM python start_by_file.py --category gui --name ExpenseSplitter.md
@REM python start_by_file.py --category gui --name FocusTime.md
@REM python start_by_file.py --category gui --name ImageEnhancer.md
@REM python start_by_file.py --category gui --name InvestmentTracker.md
@REM python start_by_file.py --category gui --name KnowledgeTracker.md
@REM python start_by_file.py --category gui --name MedicalHealthTracker.md
@REM python start_by_file.py --category gui --name NoteArchiver.md
@REM python start_by_file.py --category gui --name NotepadPlus.md
@REM python start_by_file.py --category gui --name OfficeStockManager.md
@REM python start_by_file.py --category gui --name PaintPal.md
python start_by_file.py --category gui --name PhotoStickerMaker.md
@REM python start_by_file.py --category gui --name QuickTimer.md
@REM python start_by_file.py --category gui --name RandomPasswordGenerator.md
@REM python start_by_file.py --category gui --name ScienceExperimentPlanner.md
@REM python start_by_file.py --category gui --name ScienceLibrary.md
@REM python start_by_file.py --category gui --name SecretNoteKeeper.md
@REM python start_by_file.py --category gui --name SecurePasswordVault.md
@REM python start_by_file.py --category gui --name ShapeMaster.md
@REM python start_by_file.py --category gui --name ShoppingPlanner.md
@REM python start_by_file.py --category gui --name SmartRecipt.md
@REM python start_by_file.py --category gui --name SportsEquipmentInventoryTracker.md
@REM python start_by_file.py --category gui --name TaskTracker.md
@REM python start_by_file.py --category gui --name TextSnippetOrganizer.md
@REM python start_by_file.py --category gui --name TimeConverter.md
@REM python start_by_file.py --category gui --name TimeSaver.md
@REM python start_by_file.py --category gui --name TimeTracker.md
@REM python start_by_file.py --category gui --name UnitConverter.md
pause