@echo off
@REM python start_by_file.py --category game --name 2048.md
@REM python start_by_file.py --category game --name Balls.md
@REM python start_by_file.py --category game --name BlockConnect.md
@REM python start_by_file.py --category game --name BoardGamePuzzleGenerator.md
@REM python start_by_file.py --category game --name Bomberman.md
@REM python start_by_file.py --category game --name Brick.md
@REM python start_by_file.py --category game --name ColorLinkPuzzle.md
@REM python start_by_file.py --category game --name ColorSwapChallenge.md
python start_by_file.py --category game --name DodgeFallingObjects.md
@REM python start_by_file.py --category game --name DriftRivals.md
@REM python start_by_file.py --category game --name FallingObjects.md
@REM python start_by_file.py --category game --name FlappyBirdClone.md
@REM python start_by_file.py --category game --name GemBlast.md
@REM python start_by_file.py --category game --name Ghostly.md
@REM python start_by_file.py --category game --name Gomoku.md
@REM python start_by_file.py --category game --name GravitySpeedway.md
@REM python start_by_file.py --category game --name JigsawMania.md
@REM python start_by_file.py --category game --name JumppingFrog.md
@REM python start_by_file.py --category game --name Mario.md
@REM python start_by_file.py --category game --name MazeEscapeChallenge.md
@REM python start_by_file.py --category game --name MazeRunner.md
@REM python start_by_file.py --category game --name MemoryGame.md
@REM python start_by_file.py --category game --name NumberConnect.md
@REM python start_by_file.py --category game --name NumberMystery.md
@REM python start_by_file.py --category game --name Racing.md
@REM python start_by_file.py --category game --name ShapeShifter.md
@REM python start_by_file.py --category game --name SlideMaze.md
@REM python start_by_file.py --category game --name SlidePuzzleChallenge.md
@REM python start_by_file.py --category game --name SnakeGame.md
@REM python start_by_file.py --category game --name Sokoban.md
@REM python start_by_file.py --category game --name SpaceInvaders.md
@REM python start_by_file.py --category game --name SymbolicSudoku.md
@REM python start_by_file.py --category game --name Tank.md
@REM python start_by_file.py --category game --name TargetShooter.md
@REM python start_by_file.py --category game --name TeamBuilder.md
@REM python start_by_file.py --category game --name TicTacToe.md
@REM python start_by_file.py --category game --name TilePlacer.md
@REM python start_by_file.py --category game --name TreasureHunt.md
@REM python start_by_file.py --category game --name WordGridChallenge.md
@REM python start_by_file.py --category game --name WordLinkPuzzle.md
pause