@echo off
python start_by_file.py --category game --name 2048.md --seq 666
@REM python start_by_file.py --category game --name Balls.md --seq 666
@REM python start_by_file.py --category game --name BlockConnect.md --seq 666
@REM python start_by_file.py --category game --name BoardGamePuzzleGenerator.md --seq 666
@REM python start_by_file.py --category game --name Bomberman.md --seq 666
@REM python start_by_file.py --category game --name Brick.md --seq 666
@REM python start_by_file.py --category game --name ColorLinkPuzzle.md --seq 666
@REM python start_by_file.py --category game --name ColorSwapChallenge.md --seq 666
@REM python start_by_file.py --category game --name DodgeFallingObjects.md --seq 666
@REM python start_by_file.py --category game --name DriftRivals.md --seq 666
@REM python start_by_file.py --category game --name FallingObjects.md --seq 666
@REM python start_by_file.py --category game --name FlappyBirdClone.md --seq 666
@REM python start_by_file.py --category game --name GemBlast.md --seq 666
@REM python start_by_file.py --category game --name Ghostly.md --seq 666
@REM python start_by_file.py --category game --name Gomoku.md --seq 666
@REM python start_by_file.py --category game --name GravitySpeedway.md --seq 666
@REM python start_by_file.py --category game --name JigsawMania.md --seq 666
@REM python start_by_file.py --category game --name JumppingFrog.md --seq 666
@REM python start_by_file.py --category game --name Mario.md --seq 666
@REM python start_by_file.py --category game --name MazeEscapeChallenge.md --seq 666
@REM python start_by_file.py --category game --name MazeRunner.md --seq 666
@REM python start_by_file.py --category game --name MemoryGame.md --seq 666
@REM python start_by_file.py --category game --name NumberConnect.md --seq 666
@REM python start_by_file.py --category game --name NumberMystery.md --seq 666
@REM python start_by_file.py --category game --name Racing.md --seq 666
@REM python start_by_file.py --category game --name ShapeShifter.md --seq 666
@REM python start_by_file.py --category game --name SlideMaze.md --seq 666
@REM python start_by_file.py --category game --name SlidePuzzleChallenge.md --seq 666
@REM python start_by_file.py --category game --name SnakeGame.md --seq 666
@REM python start_by_file.py --category game --name Sokoban.md --seq 666
@REM python start_by_file.py --category game --name SpaceInvaders.md --seq 666
@REM python start_by_file.py --category game --name SymbolicSudoku.md --seq 666
@REM python start_by_file.py --category game --name Tank.md --seq 666
@REM python start_by_file.py --category game --name TargetShooter.md --seq 666
@REM python start_by_file.py --category game --name TeamBuilder.md --seq 666
@REM python start_by_file.py --category game --name TicTacToe.md --seq 666
@REM python start_by_file.py --category game --name TilePlacer.md --seq 666
@REM python start_by_file.py --category game --name TreasureHunt.md --seq 666
@REM python start_by_file.py --category game --name WordGridChallenge.md --seq 666
@REM python start_by_file.py --category game --name WordLinkPuzzle.md --seq 666
pause