@echo off
@REM python start_by_file.py --category website --name BookWormSearch.md --seq 666
@REM python start_by_file.py --category website --name CharitableGivingPlatform.md --seq 666
@REM python start_by_file.py --category website --name CulturalCalendar.md --seq 666
@REM python start_by_file.py --category website --name CulturalStoryteller.md --seq 666
@REM python start_by_file.py --category website --name CultureFacts.md --seq 666
@REM python start_by_file.py --category website --name DailyHealthTips.md --seq 666
@REM python start_by_file.py --category website --name DailyJournalApp.md --seq 666
@REM python start_by_file.py --category website --name DigitalStorytellingPlatform.md --seq 666
@REM python start_by_file.py --category website --name EcoFriendlyLivingTips.md --seq 666
@REM python start_by_file.py --category website --name FreelancerMarketplace.md --seq 666
@REM python start_by_file.py --category website --name GreenLivingGuide.md --seq 666
@REM python start_by_file.py --category website --name Headlinr.md --seq 666
@REM python start_by_file.py --category website --name MedicalInfoTracker.md --seq 666
python start_by_file.py --category website --name MedicalTestResultTracker.md --seq 666
@REM python start_by_file.py --category website --name MovieRecommendationSystem.md --seq 666
@REM python start_by_file.py --category website --name NewsReader.md --seq 666
@REM python start_by_file.py --category website --name NoteTakingApp.md --seq 666
@REM python start_by_file.py --category website --name OfficeTaskFeedback.md --seq 666
@REM python start_by_file.py --category website --name OnlineLibraryManagementSystem.md --seq 666
@REM python start_by_file.py --category website --name OnlineShoppingCenter.md --seq 666
@REM python start_by_file.py --category website --name OnlineVintageMarket.md --seq 666
@REM python start_by_file.py --category website --name ParentingAdiviceForum.md --seq 666
@REM python start_by_file.py --category website --name PeerTutoringNetwork.md --seq 666
@REM python start_by_file.py --category website --name PersonalBlog.md --seq 666
@REM python start_by_file.py --category website --name QuickSearch.md --seq 666
@REM python start_by_file.py --category website --name RecipeHub.md --seq 666
@REM python start_by_file.py --category website --name RemoteJobBoard.md --seq 666
@REM python start_by_file.py --category website --name ShopPal.md --seq 666
@REM python start_by_file.py --category website --name SocialLearn.md --seq 666
@REM python start_by_file.py --category website --name SocialShare.md --seq 666
@REM python start_by_file.py --category website --name SportsEquipmentInventoryTracker.md --seq 666
@REM python start_by_file.py --category website --name TaskManager.md --seq 666
@REM python start_by_file.py --category website --name TravalMemoryShare.md --seq 666
@REM python start_by_file.py --category website --name TravalTipper.md --seq 666
@REM python start_by_file.py --category website --name TravelLog.md --seq 666
@REM python start_by_file.py --category website --name TravelRecommender.md --seq 666
@REM python start_by_file.py --category website --name TripSaver.md --seq 666
@REM python start_by_file.py --category website --name VehicleMaintenanceTracker.md --seq 666
@REM python start_by_file.py --category website --name VirtualBookPublishing.md --seq 666
@REM python start_by_file.py --category website --name WhishListTracker.md --seq 666
pause