import os
import re
import json
import ast
from pydantic import Field
from pathlib import Path
import difflib

# langchain lib
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import SystemMessage

# project's utility lib
from utils.commen import str_to_role
from utils.read import read_dir

# custom lib
from prompt.write_code_prompt import (
    CODING_SYS,
    CODING_C,
    CODING_ITE_C1,
    CODING_ITE_C2,
    RECODNIG,
)

from prompt.align_prompt import RETHINK, COMPLEMENT, ALIGN_WITH_WHO
from agents.role import Role
from agents.team import Team
from agents.searcher import Searcher
from messages.message import Message
from utils.read import read_file_2_line
from utils.edit_txt import add_newline_to_txt_files
from utils.edit_txt import update_flask_port


class C_Programmer(Role):
    name: str = "Clorinde"
    profile: str = "C_Programmer"
    llm: object
    system_msg: str = CODING_SYS
    own_message: Message = None
    team: Team = None
    # all_code_files: dict[str, list] = Field(default_factory=dict, validate_default=True)
    action: str = "Code"
    code_base: dict[str, str] = Field(default_factory=dict, validate_default=True)
    trigger_task: str = "T7"

    def go(self, ce_feedback, flag):
        # print(self.trigger_task)
        print(self.profile + " " + self.name + " Coding...")
        Team.log.info(self.profile + " " + self.name + " Coding...")

        # ---------- get the information needed from SCR ----------

        functional_requirement = self.getPRD().content
        architecture = self.getArchiture().content
        task_plan = self.getProjectPlan().content

        # --------------- decompose and assign tasks to programmer

        # ---------- constructing prompt to LLM ----------
        system_prompt = SystemMessage(content=CODING_SYS)
        # use counter prompt
        if flag == "0":
            user_prompt_template = ChatPromptTemplate.from_template(CODING_C)
            user_prompt_msg = user_prompt_template.invoke(
                {
                    "architecture": architecture,
                    "task_plan": task_plan,
                    # "functional_requirements": functional_requirement,
                }
            )
        elif flag == "1":
            exist_code = self.own_message.content
            user_prompt_template = ChatPromptTemplate.from_template(CODING_ITE_C1)
            user_prompt_msg = user_prompt_template.invoke(
                {
                    "exist_code": exist_code,
                    "ce_feedback": ce_feedback,
                }
            )
        elif flag == "2":
            exist_code = self.own_message.content
            user_prompt_template = ChatPromptTemplate.from_template(CODING_ITE_C2)
            user_prompt_msg = user_prompt_template.invoke(
                {
                    "exist_code": exist_code,
                    "ce_feedback": ce_feedback,
                }
            )

        user_prompt = user_prompt_msg.to_messages()[0]
        # prompt LLM
        Team.log.info(system_prompt.content + "\n" + user_prompt.content)
        code_result = self.llm.invoke(system_prompt, user_prompt)
        Team.log.info("\n" + code_result)
        # ________ store in self code dict ________
        self.compare_code(code_result)
        code_result_split = code_result.split("*** ")
        for i in range(1, len(code_result_split)):
            file_name, file_content = self.match(code_result_split[i])
            self.code_base[file_name] = file_content
        # self.message_to_file(code_result)

        code_msg = Message(sender=self.profile, content=code_result)
        self.own_message = code_msg

        # Team.all_messages.append(code_msg)

    def read_code_base(self):
        # code could also include other types file, like txt.
        code_sum = ""
        for key, value in self.code_base.items():
            code_sum = code_sum + "file name: " + key + "\n\n" + value + "\n\n"
        return code_sum

    def compare_code(self, code_result):
        # add code files generated by LLM to programmer's codebase
        code_result_split = code_result.split("*** ")
        differ = difflib.Differ()
        for i in range(1, len(code_result_split)):
            file_name, file_content = self.match(code_result_split[i])
            update_codes_content = "**[Update Codes]**\n\n"
            update_codes_content += "{} updated.\n".format(file_name)
            # create only if name part is not empty, to handle occasional errors with the regular expression
            if file_name:
                old_file_content = (
                    self.code_base[file_name]
                    if file_name in self.code_base.keys()
                    else "# None"
                )
            lines_old = old_file_content.splitlines()
            lines_new = file_content.splitlines()

            unified_diff = difflib.unified_diff(
                lines_old, lines_new, lineterm="", fromfile="Old", tofile="New"
            )
            unified_diff = "\n".join(unified_diff)
            update_codes_content = (
                update_codes_content
                + "\n\n"
                + """```
'''

'''\n"""
                + unified_diff
                + "\n```"
            )
            Team.log.info(update_codes_content)

    def match(self, code_text):
        """
        accept a string that has been split by ***_ (where _ represents a space).
        main.py
        ```python
        code...
        ```
        following this format, extract the name and strings separately.
        """
        pattern = r"(.*?)```"
        match = re.search(pattern, code_text, re.DOTALL)

        if match:
            before_code_block = match.group(1).strip()
        else:
            return "", ""

        # extract code
        code_pattern = r"```(?:\w+)?(.*?)(?:```|$)"
        code_match = re.search(code_pattern, code_text, re.DOTALL)

        if code_match:
            code_block = code_match.group(1).strip()
            return before_code_block, code_block
        else:
            return "", ""

    def write_adapator(self, file_dict):
        """
        will be removed in futurn
        """
        result = ""
        for key, value in file_dict.items():
            result = result + "*** " + key + "\n```placeholder\n" + value + "\n```\n\n"
        return result

    def message_to_file(self, code_text):
        if not os.path.exists(os.path.join(Team.project_dir, "code")):
            # makedir_s, recursely create folders
            os.makedirs(os.path.join(Team.project_dir, "code"))
        code_base_dir = os.path.join(Team.project_dir, "code")
        # split based on ***_
        code_text_split = code_text.split("*** ")

        for i in range(1, len(code_text_split)):
            name, code = self.match(code_text_split[i])
            # create only if name part is not empty, to handle occasional errors with the regular expression
            if name:
                # if name contains a directory, create it
                file_relative_directory = os.path.dirname(name)
                code_dir = os.path.join(code_base_dir, file_relative_directory)
                if not os.path.exists(code_dir):
                    # makedir_s, recursely create folders
                    os.makedirs(code_dir)
                # writing result to local
                print(self.profile + " writting CODE: " + str(name))
                Team.log.info(self.profile + " writting CODE: " + str(name))
                super().save_file_overwrite(
                    os.path.join(code_base_dir, str(name)), str(code)
                )

        add_newline_to_txt_files(code_base_dir)
        # update_flask_port(os.path.join(code_base_dir, "main.py"))

    def message_to_file_review(self, code_text):
        os.makedirs(Team.project_dir + "review_code")
        code_base_dir = Team.project_dir + "review_code/"
        # split based on ###_
        code_text_split = code_text.split("### ")

        for i in range(1, len(code_text_split)):
            name, code = self.match(code_text_split[i])
            # create only if name part is not empty, to handle occasional errors with the regular expression
            if name:
                # if name contains a directory, create it
                file_relative_directory = os.path.dirname(name)
                code_dir = code_base_dir + file_relative_directory
                if not os.path.exists(code_dir):
                    # makedir_s, recursely create folders
                    os.makedirs(code_dir)
                # writing result to local
                print(self.profile + " Rewritting CODE: " + str(name))
                Team.log.info(self.profile + " Rewritting CODE: " + str(name))
                super().save_file_overwrite(code_base_dir + str(name), str(code))

    def message_to_file_test(self, code_text):
        if not os.path.exists(Team.project_dir + "test_code"):
            os.makedirs(Team.project_dir + "test_code")
        # split based on ###_
        code_base_dir = Team.project_dir + "test_code/"
        code_text_split = code_text.split("*** ")

        for i in range(1, len(code_text_split)):
            name, code = self.match(code_text_split[i])
            # create only if name part is not empty, to handle occasional errors with the regular expression
            if name:
                # if name contains a directory, create it
                file_relative_directory = os.path.dirname(name)
                code_dir = code_base_dir + file_relative_directory
                if not os.path.exists(code_dir):
                    # makedir_s, recursely create folders
                    os.makedirs(code_dir)
                # writing result to local
                print(self.profile + " writting Test CODE: " + str(name))
                Team.log.info(self.profile + " writting Test CODE: " + str(name))
                super().save_file_overwrite(code_base_dir + str(name), str(code))

        add_newline_to_txt_files(code_base_dir)
        update_flask_port(os.path.join(code_base_dir, "main.py"))

    def update_own_message(self, msg: Message):
        self.own_message = msg
        Team.all_messages[4] = msg

    def get_align_roles(self, self_content):
        Team.log.info("Team's Active roles: " + Team.active_roles)
        # if not the first role
        if Team.active_roles:
            system_prompt = SystemMessage(
                content="You are a good software engineering expert"
            )
            user_prompt_template = ChatPromptTemplate.from_template(ALIGN_WITH_WHO)
            user_prompt_msg = user_prompt_template.invoke(
                {
                    "role": self.profile,
                    "other_rule_content": self.read_msg(Team.all_messages[1:]),
                    "role_action": self.action,
                    "role_content": self_content,
                    "roles_list": Team.active_roles,
                }
            )
            user_prompt = user_prompt_msg.to_messages()[0]
            Team.log.info("search Align roles's prompt: " + user_prompt.content)
            align_roles_llm_result = self.llm.invoke(system_prompt, user_prompt)
            Team.log.info(
                "LLM think Alignment Group Members: " + align_roles_llm_result
            )
            dict_obj = json.loads(align_roles_llm_result)
            print("Format Group Members: " + str(dict_obj["roles"]))

            roles_list = dict_obj["roles"]
            return roles_list
        else:
            return "HUMAN"

    # programmer won't add self's message, no need to filter messages;
    def read_msg(self, messages):
        result = ""
        for msg in messages:
            result = (
                result
                + "# "
                + msg.sender
                + " - "
                + self.team.roles[msg.sender].action
                + "\n"
                + msg.content
                + "\n"
            )
        return result

    def read_suggestion(self, suggestion):
        # accept a Message List
        # return a more friendly result(String type)
        # User's review: xxx, User's review xxx
        result = ""
        for msg in suggestion:
            result = (
                result + "[ " + msg.sender + "'s code review: " + msg.content + " ]\n"
            )
        return result

    def getOriginalDescription(self):
        return Team.all_messages[0]

    def getPRD(self):
        return Team.all_messages[1]

    def getArchiture(self):
        return Team.all_messages[2]

    def getProjectPlan(self):
        return Team.all_messages[3]

    def go_inter(self):
        pass
