# change to your api_key & base_url
llm_3_5:
  api_type: "openai"
  base_url: ""
  api_key: ""
  model: "gpt-3.5-turbo-16k"
  # temperature: 0.2
  programmer_temperature: 0.2

llm_4o:
  api_type: "openai"
  base_url: "https://api.chatanywhere.tech"
  api_key: "sk-1SP4KiEAcGrjEnK6ppxolAHciQdJU0n8AhL8xmO1AogtJk9g" # "sk-BMbYMWUZe18kwEsqxNA9wUBBxmyMbFOToVBgIf4fmWxcYTXs"
  model: "gpt-4o-mini"
  temperature: 0.2
  sampling_temperature: 0.4



tavily:
  api_key:

LangChainHub:

Qwen:
  api_key: ""
